In [1]:
import numpy
import pandas as pd

data= 'vine_table.csv'

In [3]:
vine_df = pd.read_csv(data, index_col= False)
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,RDIJS7QYB6XNR,5.0,0.0,0.0,N,Y
1,R36ED1U38IELG8,5.0,0.0,0.0,N,Y
2,R1UE3RPRGCOLD,2.0,1.0,1.0,N,Y
3,R298788GS6I901,5.0,0.0,0.0,N,Y
4,RNX4EXOBBPN5,1.0,1.0,1.0,N,Y
...,...,...,...,...,...,...
4864244,R1UP8F8Y4GC3IE,4.0,0.0,1.0,N,N
4864245,R3K9ZYANG0OFJB,5.0,7.0,7.0,N,N
4864246,R17ULZ2VC0O3CG,4.0,23.0,23.0,N,N
4864247,R13AWVNEKSY9M1,5.0,5.0,5.0,N,N
4864248,R1HN7EVNEN51LR,4.0,2.0,7.0,N,N